serviceType: NodePort
port: 80
replicas: 1
imageLabel: IMAGE_LABEL
registry: ACR_URL
resources:
  limits:
    cpu: 500m
    memory: 128Mi
ingressEnabled: true
ingressAnnotations:
  kubernetes.io/ingress.class: addon-http-application-routing
ingressHost: atthehelm.AKS_URL
