apiVersion: v1
kind: Service
metadata:
  name: atthehelm
spec:
  type: NodePort
  selector:
    app: atthehelm
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atthehelm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atthehelm
  template:
    metadata:
      labels:
        app: atthehelm
        version: IMAGE_LABEL
    spec:
      containers:
      - name: atthehelm
        image: ACR_URL/atthehelm:IMAGE_LABEL
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atthehelm
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
  - host: atthehelm.AKS_URL
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: atthehelm
            port:
              number: 80
