apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        version: {{ .Values.imageLabel }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: '{{ if .Values.registry -}}{{ .Values.registry }}/{{- end -}}{{ .Chart.Name }}:{{ .Values.imageLabel }}'
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
