apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
